/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Soutenance1;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Game start = new Game();
    }
}
